version: "3"

services:
  follower-maze:
    image: golang:1.20-alpine
    ports:
      - "9090:9090"
      - "9099:9099"
    volumes:
      - .:/follower-maze
    working_dir: /follower-maze
    command: [ "tail", "-f", "/dev/null" ]
